name: wildfire
description: An empty Liquidart application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  liquidart: ^4.0.0-b1

dev_dependencies:
  test: ^1.0.0
  liquidart_test: ^2.0.0-b1